export type ComponentTaxonomyNode = {
  readonly name: string;
  readonly slug: string;
  readonly parentSlug: string | null;
  readonly path: string;
  readonly depth: number;
  readonly aliases: readonly string[];
  readonly description: string;
  readonly isLeaf: boolean;
};

export const COMPONENT_TAXONOMY_VERSION = "component-taxonomy-v1";

export const COMPONENT_TAXONOMY = [
  {
    name: "Rotating Machinery",
    slug: "rotating-machinery",
    parentSlug: null,
    path: "rotating-machinery",
    depth: 0,
    aliases: [],
    description: "Components that rotate during operation",
    isLeaf: false,
  },
  {
    name: "Static Structures",
    slug: "static-structures",
    parentSlug: null,
    path: "static-structures",
    depth: 0,
    aliases: [],
    description: "Non-rotating structural components",
    isLeaf: false,
  },
  {
    name: "Fluid Systems",
    slug: "fluid-systems",
    parentSlug: null,
    path: "fluid-systems",
    depth: 0,
    aliases: [],
    description: "Pumps, valves, seals, pipes and fluid circuits",
    isLeaf: false,
  },
  {
    name: "Electrical Systems",
    slug: "electrical-systems",
    parentSlug: null,
    path: "electrical-systems",
    depth: 0,
    aliases: [],
    description: "Electrical and power conversion components",
    isLeaf: false,
  },
  {
    name: "Aero/Thermo Surfaces",
    slug: "aero-thermo-surfaces",
    parentSlug: null,
    path: "aero-thermo-surfaces",
    depth: 0,
    aliases: [],
    description: "Blades, vanes, and thermally loaded surfaces",
    isLeaf: false,
  },
  {
    name: "Joints and Fasteners",
    slug: "joints-fasteners",
    parentSlug: null,
    path: "joints-fasteners",
    depth: 0,
    aliases: [],
    description: "Bolts, welds, and structural joints",
    isLeaf: false,
  },
  {
    name: "Bearing",
    slug: "bearing",
    parentSlug: "rotating-machinery",
    path: "rotating-machinery/bearing",
    depth: 1,
    aliases: ["bearings", "rolling bearing", "plain bearing", "sleeve bearing"],
    description: "Load-carrying element between two surfaces in relative motion",
    isLeaf: false,
  },
  {
    name: "Gearbox",
    slug: "gearbox",
    parentSlug: "rotating-machinery",
    path: "rotating-machinery/gearbox",
    depth: 1,
    aliases: ["gear box", "gear train", "gears", "geartrain"],
    description: "Power transmission assembly of meshing gears",
    isLeaf: false,
  },
  {
    name: "Shaft",
    slug: "shaft",
    parentSlug: "rotating-machinery",
    path: "rotating-machinery/shaft",
    depth: 1,
    aliases: ["shafts", "rotor shaft", "drive shaft", "spindle", "axle"],
    description: "Rotating cylindrical member transmitting torque",
    isLeaf: true,
  },
  {
    name: "Gear",
    slug: "gear",
    parentSlug: "rotating-machinery",
    path: "rotating-machinery/gear",
    depth: 1,
    aliases: ["gears", "gear tooth", "tooth", "gear teeth", "pinion", "helical gear", "spur gear"],
    description: "Individual toothed wheel in a gear train",
    isLeaf: true,
  },
  {
    name: "Rolling Element Bearing",
    slug: "rolling-element-bearing",
    parentSlug: "bearing",
    path: "rotating-machinery/bearing/rolling-element-bearing",
    depth: 2,
    aliases: ["rolling bearing", "anti-friction bearing", "roller bearing"],
    description: "Bearing using rolling elements between races",
    isLeaf: false,
  },
  {
    name: "Plain Bearing",
    slug: "plain-bearing",
    parentSlug: "bearing",
    path: "rotating-machinery/bearing/plain-bearing",
    depth: 2,
    aliases: ["sleeve bearing", "journal bearing", "bushing", "bushings", "plain bearings"],
    description: "Bearing relying on a sliding contact surface",
    isLeaf: true,
  },
  {
    name: "Ball Bearing",
    slug: "ball-bearing",
    parentSlug: "rolling-element-bearing",
    path: "rotating-machinery/bearing/rolling-element-bearing/ball-bearing",
    depth: 3,
    aliases: ["ball bearings", "deep groove ball bearing", "angular contact bearing", "deep-groove ball bearing"],
    description: "Rolling element bearing using balls",
    isLeaf: true,
  },
  {
    name: "Cylindrical Roller Bearing",
    slug: "cylindrical-roller-bearing",
    parentSlug: "rolling-element-bearing",
    path: "rotating-machinery/bearing/rolling-element-bearing/cylindrical-roller-bearing",
    depth: 3,
    aliases: ["cylindrical roller bearings", "cylindrical roller bearing"],
    description: "Roller bearing with cylindrical rolling elements",
    isLeaf: true,
  },
  {
    name: "Tapered Roller Bearing",
    slug: "tapered-roller-bearing",
    parentSlug: "rolling-element-bearing",
    path: "rotating-machinery/bearing/rolling-element-bearing/tapered-roller-bearing",
    depth: 3,
    aliases: ["tapered roller bearings", "taper bearing", "tapered bearing"],
    description: "Roller bearing for combined axial and radial load",
    isLeaf: true,
  },
  {
    name: "Thrust Bearing",
    slug: "thrust-bearing",
    parentSlug: "rolling-element-bearing",
    path: "rotating-machinery/bearing/rolling-element-bearing/thrust-bearing",
    depth: 3,
    aliases: ["thrust bearings", "axial bearing"],
    description: "Bearing designed primarily for axial loads",
    isLeaf: true,
  },
  {
    name: "Main Shaft Bearing",
    slug: "main-shaft-bearing",
    parentSlug: "rolling-element-bearing",
    path: "rotating-machinery/bearing/rolling-element-bearing/main-shaft-bearing",
    depth: 3,
    aliases: ["main bearing", "main bearings", "main shaft bearing", "LSS bearing", "low-speed shaft bearing"],
    description: "Large-diameter bearing on the primary shaft",
    isLeaf: true,
  },
  {
    name: "Accessory Gearbox",
    slug: "accessory-gearbox",
    parentSlug: "gearbox",
    path: "rotating-machinery/gearbox/accessory-gearbox",
    depth: 2,
    aliases: ["AGB", "accessory gear box", "accessory drive gearbox", "aircraft accessory gearbox"],
    description: "Drives engine accessories such as fuel pumps, oil pumps, and generators",
    isLeaf: true,
  },
  {
    name: "Reduction Gearbox",
    slug: "reduction-gearbox",
    parentSlug: "gearbox",
    path: "rotating-machinery/gearbox/reduction-gearbox",
    depth: 2,
    aliases: ["reduction gear", "speed reducer", "step-down gearbox", "main gearbox"],
    description: "Steps down rotational speed",
    isLeaf: true,
  },
  {
    name: "Epicyclic Gearbox",
    slug: "epicyclic-gearbox",
    parentSlug: "gearbox",
    path: "rotating-machinery/gearbox/epicyclic-gearbox",
    depth: 2,
    aliases: ["planetary gearbox", "planetary gear", "epicyclic gear", "planetary gear train"],
    description: "Compact multi-stage gear arrangement with planet gears",
    isLeaf: true,
  },
  {
    name: "Blade",
    slug: "blade",
    parentSlug: "aero-thermo-surfaces",
    path: "aero-thermo-surfaces/blade",
    depth: 1,
    aliases: ["blades", "aerofoil", "airfoil"],
    description: "Aerofoil section within a turbomachine or rotor system",
    isLeaf: false,
  },
  {
    name: "Turbine Blade",
    slug: "turbine-blade",
    parentSlug: "blade",
    path: "aero-thermo-surfaces/blade/turbine-blade",
    depth: 2,
    aliases: [
      "turbine blades",
      "HP turbine blade",
      "LP turbine blade",
      "high-pressure turbine blade",
      "low-pressure turbine blade",
      "nozzle guide vane",
      "NGV",
      "rotor blade",
    ],
    description: "Rotating or static aerofoil within a turbine stage",
    isLeaf: true,
  },
  {
    name: "Fan Blade",
    slug: "fan-blade",
    parentSlug: "blade",
    path: "aero-thermo-surfaces/blade/fan-blade",
    depth: 2,
    aliases: ["fan blades", "fan aerofoil", "fan rotor blade", "wide-chord fan blade"],
    description: "First-stage wide-chord blade on a turbofan engine",
    isLeaf: true,
  },
  {
    name: "Compressor Blade",
    slug: "compressor-blade",
    parentSlug: "blade",
    path: "aero-thermo-surfaces/blade/compressor-blade",
    depth: 2,
    aliases: ["compressor blades", "stator vane", "compressor vane", "HP compressor blade", "LP compressor blade", "IPC blade", "HPC blade"],
    description: "Blade in a compressor stage",
    isLeaf: true,
  },
  {
    name: "Wind Turbine Blade",
    slug: "wind-turbine-blade",
    parentSlug: "blade",
    path: "aero-thermo-surfaces/blade/wind-turbine-blade",
    depth: 2,
    aliases: ["wind blade", "WTG blade", "turbine rotor blade", "rotor blade", "wind turbine rotor blade"],
    description: "Large composite blade on a wind turbine rotor",
    isLeaf: true,
  },
  {
    name: "Combustor",
    slug: "combustor",
    parentSlug: "aero-thermo-surfaces",
    path: "aero-thermo-surfaces/combustor",
    depth: 1,
    aliases: ["combustion chamber", "burner", "flame tube", "liner", "combustion liner"],
    description: "Chamber where fuel combustion occurs in a gas turbine",
    isLeaf: true,
  },
  {
    name: "Nozzle",
    slug: "nozzle",
    parentSlug: "aero-thermo-surfaces",
    path: "aero-thermo-surfaces/nozzle",
    depth: 1,
    aliases: ["jet nozzle", "exhaust nozzle", "turbine nozzle", "nozzle guide vane", "convergent nozzle"],
    description: "Flow-directing or thrust-generating component",
    isLeaf: true,
  },
  {
    name: "Pump",
    slug: "pump",
    parentSlug: "fluid-systems",
    path: "fluid-systems/pump",
    depth: 1,
    aliases: ["pumps"],
    description: "Device that moves fluid by mechanical action",
    isLeaf: false,
  },
  {
    name: "Centrifugal Pump",
    slug: "centrifugal-pump",
    parentSlug: "pump",
    path: "fluid-systems/pump/centrifugal-pump",
    depth: 2,
    aliases: ["centrifugal pumps", "radial pump"],
    description: "Pump using centrifugal force to move fluid",
    isLeaf: true,
  },
  {
    name: "Oil Pump",
    slug: "oil-pump",
    parentSlug: "pump",
    path: "fluid-systems/pump/oil-pump",
    depth: 2,
    aliases: ["oil pumps", "scavenge pump", "pressure pump", "lube pump", "lubrication pump"],
    description: "Lubricant circulation pump in engine or gearbox",
    isLeaf: true,
  },
  {
    name: "Fuel Pump",
    slug: "fuel-pump",
    parentSlug: "pump",
    path: "fluid-systems/pump/fuel-pump",
    depth: 2,
    aliases: ["fuel pumps", "high-pressure fuel pump", "HP fuel pump", "fuel feed pump"],
    description: "Pump pressurising fuel for combustion",
    isLeaf: true,
  },
  {
    name: "Valve",
    slug: "valve",
    parentSlug: "fluid-systems",
    path: "fluid-systems/valve",
    depth: 1,
    aliases: ["valves", "check valve", "control valve", "relief valve", "safety valve", "solenoid valve", "PRV", "PSV", "ball valve", "gate valve"],
    description: "Device regulating or controlling flow of fluid",
    isLeaf: true,
  },
  {
    name: "Seal",
    slug: "seal",
    parentSlug: "fluid-systems",
    path: "fluid-systems/seal",
    depth: 1,
    aliases: ["seals", "gasket", "O-ring", "sealing element", "lip seal"],
    description: "Component preventing leakage between interfaces",
    isLeaf: false,
  },
  {
    name: "Mechanical Seal",
    slug: "mechanical-seal",
    parentSlug: "seal",
    path: "fluid-systems/seal/mechanical-seal",
    depth: 2,
    aliases: ["mechanical seals", "face seal", "rotating seal", "carbon seal", "carbon face seal"],
    description: "Seal using sliding contact between faces",
    isLeaf: true,
  },
  {
    name: "Labyrinth Seal",
    slug: "labyrinth-seal",
    parentSlug: "seal",
    path: "fluid-systems/seal/labyrinth-seal",
    depth: 2,
    aliases: ["labyrinth seals", "labyrinth", "air seal", "knife-edge seal"],
    description: "Non-contact seal using tortuous flow path",
    isLeaf: true,
  },
  {
    name: "Pipe",
    slug: "pipe",
    parentSlug: "fluid-systems",
    path: "fluid-systems/pipe",
    depth: 1,
    aliases: ["pipes", "pipeline", "tube", "tubing", "conduit", "piping", "flow line", "riser"],
    description: "Conduit for fluid transport",
    isLeaf: true,
  },
  {
    name: "Power Converter",
    slug: "power-converter",
    parentSlug: "electrical-systems",
    path: "electrical-systems/power-converter",
    depth: 1,
    aliases: ["converter", "inverter", "power electronics", "variable frequency drive", "VFD", "frequency converter", "power module"],
    description: "Electronic device converting electrical power between forms",
    isLeaf: true,
  },
  {
    name: "Battery Cell",
    slug: "battery-cell",
    parentSlug: "electrical-systems",
    path: "electrical-systems/battery-cell",
    depth: 1,
    aliases: ["battery", "cell", "lithium-ion cell", "module", "battery pack", "energy storage cell", "Li-ion cell", "LIB"],
    description: "Electrochemical cell storing electrical energy",
    isLeaf: true,
  },
  {
    name: "Sensor",
    slug: "sensor",
    parentSlug: "electrical-systems",
    path: "electrical-systems/sensor",
    depth: 1,
    aliases: ["sensors", "temperature sensor", "pressure sensor", "vibration sensor", "accelerometer", "transducer", "probe", "thermocouple"],
    description: "Device detecting physical conditions and converting to a signal",
    isLeaf: true,
  },
  {
    name: "Bolt",
    slug: "bolt",
    parentSlug: "joints-fasteners",
    path: "joints-fasteners/bolt",
    depth: 1,
    aliases: ["bolts", "fastening bolt", "structural bolt", "stud bolt", "cap screw", "fastener", "threaded fastener"],
    description: "Threaded fastener used to join structural components",
    isLeaf: true,
  },
  {
    name: "Weld",
    slug: "weld",
    parentSlug: "joints-fasteners",
    path: "joints-fasteners/weld",
    depth: 1,
    aliases: ["welds", "welded joint", "weld joint", "weld seam", "weld toe", "heat-affected zone", "HAZ"],
    description: "Fusion joint formed by melting and solidifying material",
    isLeaf: true,
  },
  {
    name: "Spring",
    slug: "spring",
    parentSlug: "joints-fasteners",
    path: "joints-fasteners/spring",
    depth: 1,
    aliases: ["springs", "coil spring", "leaf spring", "return spring", "valve spring"],
    description: "Elastic element storing mechanical energy",
    isLeaf: true,
  },
] as const satisfies readonly ComponentTaxonomyNode[];

function normalizeTaxonomyText(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[_/]+/g, " ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function findComponentTaxonomyNode(value: string | null | undefined) {
  if (!value) return null;
  const trimmed = value.trim();
  const normalized = normalizeTaxonomyText(trimmed);
  if (!normalized) return null;

  return (
    COMPONENT_TAXONOMY.find((node) => node.slug === trimmed || normalizeTaxonomyText(node.slug) === normalized) ??
    COMPONENT_TAXONOMY.find((node) => normalizeTaxonomyText(node.name) === normalized) ??
    COMPONENT_TAXONOMY.find((node) =>
      node.aliases.some((alias) => normalizeTaxonomyText(alias) === normalized),
    ) ??
    null
  );
}

export function componentTaxonomyChildren(parentSlug: string | null = null) {
  return COMPONENT_TAXONOMY.filter((node) => node.parentSlug === parentSlug);
}
